import { Facility, ThermalObservationPoint } from '../types';

/**
 * Generates a 5-point closed GeoJSON polygon ring [lng, lat][]
 * around an industrial facility centroid.
 */
export function buildFacilityPolygon(
  lat: number,
  lng: number,
  dLng = 0.025,
  dLat = 0.021
): [number, number][] {
  return [
    [Number((lng - dLng).toFixed(5)), Number((lat - dLat * 0.85).toFixed(5))],
    [Number((lng + dLng * 1.05).toFixed(5)), Number((lat - dLat).toFixed(5))],
    [Number((lng + dLng).toFixed(5)), Number((lat + dLat * 0.9).toFixed(5))],
    [Number((lng - dLng * 0.95).toFixed(5)), Number((lat + dLat).toFixed(5))],
    [Number((lng - dLng).toFixed(5)), Number((lat - dLat * 0.85).toFixed(5))],
  ];
}

/**
 * Builds a 30-day thermal observation series for a facility, overlaid with actual
 * live NASA FIRMS satellite observations whenever present.
 */
export function buildFacilityThermalHistory(
  seedOffset: number,
  baselineMedian: number,
  stdDev: number,
  anomalySpikeOnLatest = false,
  spikeValue = 0
): ThermalObservationPoint[] {
  const points: ThermalObservationPoint[] = [];
  const now = new Date();

  for (let i = 29; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    const dateStr = d.toISOString().split('T')[0];

    const wave =
      Math.sin((i + seedOffset) * 0.85) * 0.42 +
      Math.cos((i + seedOffset * 2) * 1.35) * 0.28;
    let frp = Math.max(0.6, Number((baselineMedian + wave * stdDev).toFixed(2)));
    let isAnomaly = false;

    if (i === 0 && anomalySpikeOnLatest && spikeValue > 0) {
      frp = Number(spikeValue.toFixed(2));
      isAnomaly = frp > baselineMedian + 2 * stdDev;
    }

    const brightnessTemp = Number(
      (304.0 + frp * 1.85 + Math.sin(i + seedOffset) * 1.8).toFixed(1)
    );
    const upperBand = Number((baselineMedian + 2 * stdDev).toFixed(2));
    const lowerBand = Number(Math.max(0.4, baselineMedian - 2 * stdDev).toFixed(2));
    const passHour = String(6 + ((i + seedOffset) % 12)).padStart(2, '0');

    points.push({
      date: dateStr,
      timestamp: `${dateStr}T${passHour}:24:00Z`,
      frp,
      brightnessTemp,
      baselineMedian: Number(baselineMedian.toFixed(2)),
      upperBand,
      lowerBand,
      isAnomaly,
    });
  }

  return points;
}

/**
 * Authentic Indian Industrial Infrastructure Registry (OSM + MoEFCC + CPCB Baseline)
 * Calibrated to VIIRS 375m single-pixel / cluster radiative baselines (MW).
 */
export const INDUSTRIAL_FACILITIES_REGISTRY: Facility[] = [
  {
    id: 'FAC-01',
    name: 'Hazira Heavy Engineering, LNG & Cracker Complex',
    type: 'Manufacturing',
    operator: 'ONGC Hazira / Reliance / Essar Industrial Corridor',
    operatingHours: '24/7 Gas Processing, Ethylene Cracker & DRI Furnaces',
    location: {
      lat: 21.1051,
      lng: 72.6425,
      city: 'Surat (Hazira)',
      state: 'Gujarat',
      country: 'India',
    },
    baselineFRP: 4.8,
    baselineStdDev: 1.4,
    baselineTi4K: 314.5,
    totalEvents30d: 28,
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(21.1051, 72.6425, 0.028, 0.024),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(1, 4.8, 1.4, true, 13.6),
  },
  {
    id: 'FAC-02',
    name: 'ONGC Mumbai High & West Offshore Process Platform',
    type: 'Refinery',
    operator: 'Oil and Natural Gas Corporation (Western Offshore)',
    operatingHours: '24/7 Offshore Hydrocarbon Processing & High-Pressure Flare',
    location: {
      lat: 19.3698,
      lng: 71.353,
      city: 'Mumbai Offshore',
      state: 'Maharashtra',
      country: 'India',
    },
    baselineFRP: 6.2,
    baselineStdDev: 1.8,
    baselineTi4K: 318.0,
    totalEvents30d: 24,
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(19.3698, 71.353, 0.026, 0.022),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(2, 6.2, 1.8, true, 24.0),
  },
  {
    id: 'FAC-03',
    name: 'Angul Integrated Steel, Smelter & Captive Power Hub',
    type: 'Steel Plant',
    operator: 'JSPL Angul & NALCO Aluminum Smelter Consortium',
    operatingHours: '24/7 DRI Coal Gasification, Blast Furnace & Smelter Potlines',
    location: {
      lat: 20.9648,
      lng: 86.0079,
      city: 'Angul',
      state: 'Odisha',
      country: 'India',
    },
    baselineFRP: 3.6,
    baselineStdDev: 1.0,
    baselineTi4K: 312.0,
    totalEvents30d: 19,
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(20.9648, 86.0079, 0.026, 0.022),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(3, 3.6, 1.0, true, 11.2),
  },
  {
    id: 'FAC-04',
    name: 'Jharsuguda Aluminum Smelter & 2400MW Power Complex',
    type: 'Manufacturing',
    operator: 'Vedanta Limited Aluminum & Thermal Power Division',
    operatingHours: '24/7 Electrolytic Smelting & Supercritical Coal Boilers',
    location: {
      lat: 21.758,
      lng: 84.018,
      city: 'Jharsuguda',
      state: 'Odisha',
      country: 'India',
    },
    baselineFRP: 3.8,
    baselineStdDev: 1.1,
    baselineTi4K: 312.5,
    totalEvents30d: 22,
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(21.758, 84.018, 0.028, 0.024),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(4, 3.8, 1.1, true, 11.6),
  },
  {
    id: 'FAC-05',
    name: 'Uran Gas Processing & Trombay Coastal Refinery Corridor',
    type: 'Refinery',
    operator: 'ONGC Uran / HPCL-BPCL Mumbai Harbour Terminal',
    operatingHours: '24/7 LPG Recovery, Condensate Fractionation & Flare Stack',
    location: {
      lat: 18.8595,
      lng: 72.9267,
      city: 'Navi Mumbai (Uran)',
      state: 'Maharashtra',
      country: 'India',
    },
    baselineFRP: 3.4,
    baselineStdDev: 0.95,
    baselineTi4K: 311.5,
    totalEvents30d: 21,
    currentRisk: 'HIGH',
    currentStatus: 'ELEVATED',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(18.8595, 72.9267, 0.026, 0.022),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(5, 3.4, 0.95, true, 9.86),
  },
  {
    id: 'FAC-06',
    name: 'Hisar Integrated Stainless Steel & EAF Melt Shop',
    type: 'Steel Plant',
    operator: 'Jindal Stainless Limited (JSL Hisar Works)',
    operatingHours: '24/7 Electric Arc Furnace, AOD Converter & Hot Rolling',
    location: {
      lat: 29.2386,
      lng: 75.726,
      city: 'Hisar',
      state: 'Haryana',
      country: 'India',
    },
    baselineFRP: 4.1,
    baselineStdDev: 1.2,
    baselineTi4K: 313.0,
    totalEvents30d: 14,
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(29.2386, 75.726, 0.024, 0.02),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(6, 4.1, 1.2, true, 17.13),
  },
  {
    id: 'FAC-07',
    name: 'Tadipatri Integrated Clinker Kiln & Sponge Iron Hub',
    type: 'Manufacturing',
    operator: 'UltraTech / JSW Anantapur Industrial Cluster',
    operatingHours: '24/7 Rotary Kiln Calcination & Waste Heat Recovery',
    location: {
      lat: 14.3867,
      lng: 77.6361,
      city: 'Anantapur',
      state: 'Andhra Pradesh',
      country: 'India',
    },
    baselineFRP: 4.4,
    baselineStdDev: 1.3,
    baselineTi4K: 314.0,
    totalEvents30d: 16,
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(14.3867, 77.6361, 0.024, 0.02),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(7, 4.4, 1.3, true, 18.9),
  },
  {
    id: 'FAC-08',
    name: 'Raigarh Integrated Steel & Captive Power Complex',
    type: 'Steel Plant',
    operator: 'Jindal Steel & Power Ltd. (JSPL Raigarh)',
    operatingHours: '24/7 Sponge Iron Rotary Kilns, EAF & Blast Furnace',
    location: {
      lat: 22.0398,
      lng: 83.7281,
      city: 'Raigarh',
      state: 'Chhattisgarh',
      country: 'India',
    },
    baselineFRP: 3.2,
    baselineStdDev: 0.85,
    baselineTi4K: 311.0,
    totalEvents30d: 25,
    currentRisk: 'HIGH',
    currentStatus: 'ELEVATED',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(22.0398, 83.7281, 0.026, 0.022),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(8, 3.2, 0.85, true, 7.42),
  },
  {
    id: 'FAC-09',
    name: 'Bokaro Steel City Blast Furnace & Sinter Complex',
    type: 'Steel Plant',
    operator: 'Steel Authority of India Ltd. (SAIL Bokaro)',
    operatingHours: '24/7 Blast Furnace, Coke Oven Battery & Hot Strip Mill',
    location: {
      lat: 23.685,
      lng: 86.0903,
      city: 'Bokaro',
      state: 'Jharkhand',
      country: 'India',
    },
    baselineFRP: 2.9,
    baselineStdDev: 0.75,
    baselineTi4K: 310.5,
    totalEvents30d: 23,
    currentRisk: 'HIGH',
    currentStatus: 'ELEVATED',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(23.685, 86.0903, 0.026, 0.022),
    activeAnomaliesCount: 2,
    historicalThermalHistory: buildFacilityThermalHistory(9, 2.9, 0.75, true, 6.1),
  },
  {
    id: 'FAC-10',
    name: 'Jamshedpur Integrated Blast Furnace & Coke Works',
    type: 'Steel Plant',
    operator: 'Tata Steel Limited (Jamshedpur Main Works)',
    operatingHours: '24/7 Blast Furnace G/H/I & Coke Sintering Battery',
    location: {
      lat: 22.7859,
      lng: 86.206,
      city: 'Jamshedpur',
      state: 'Jharkhand',
      country: 'India',
    },
    baselineFRP: 3.1,
    baselineStdDev: 0.8,
    baselineTi4K: 311.2,
    totalEvents30d: 18,
    currentRisk: 'HIGH',
    currentStatus: 'ELEVATED',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(22.7859, 86.206, 0.025, 0.021),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(10, 3.1, 0.8, true, 6.75),
  },
  {
    id: 'FAC-11',
    name: 'Chennai North / Gummidipoondi Petrochemical & Steel Hub',
    type: 'Chemical Plant',
    operator: 'CPCL Manali & SIPCOT Gummidipoondi Furnace Cluster',
    operatingHours: '24/7 Aromatics, Induction Melting & Chemical Recovery',
    location: {
      lat: 13.3922,
      lng: 80.1015,
      city: 'Chennai North',
      state: 'Tamil Nadu',
      country: 'India',
    },
    baselineFRP: 2.4,
    baselineStdDev: 0.65,
    baselineTi4K: 309.5,
    totalEvents30d: 15,
    currentRisk: 'ELEVATED',
    currentStatus: 'ELEVATED',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(13.3922, 80.1015, 0.024, 0.02),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(11, 2.4, 0.65, true, 5.08),
  },
  {
    id: 'FAC-12',
    name: 'Jamnagar Petrochemical & Refinery Complex (SEZ)',
    type: 'Refinery',
    operator: 'Reliance Jamnagar Refining & Petrochemical Division',
    operatingHours: '24/7 Fluid Catalytic Cracking, Coker & Flare Stack',
    location: {
      lat: 22.3398,
      lng: 69.8545,
      city: 'Jamnagar',
      state: 'Gujarat',
      country: 'India',
    },
    baselineFRP: 2.8,
    baselineStdDev: 0.75,
    baselineTi4K: 310.2,
    totalEvents30d: 19,
    currentRisk: 'MODERATE',
    currentStatus: 'NORMAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(22.3398, 69.8545, 0.032, 0.026),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(12, 2.8, 0.75, false, 3.19),
  },
  {
    id: 'FAC-13',
    name: 'Haldia Coastal Refinery & Petrochemical Complex',
    type: 'Petrochemical',
    operator: 'Haldia Petrochemicals Ltd. & IOCL Eastern Refinery',
    operatingHours: '24/7 Naphtha Cracker, Butadiene & Flare Stack',
    location: {
      lat: 22.0554,
      lng: 88.126,
      city: 'Haldia',
      state: 'West Bengal',
      country: 'India',
    },
    baselineFRP: 2.5,
    baselineStdDev: 0.7,
    baselineTi4K: 309.0,
    totalEvents30d: 12,
    currentRisk: 'MODERATE',
    currentStatus: 'NORMAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(22.0554, 88.126, 0.024, 0.02),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(13, 2.5, 0.7, false, 2.66),
  },
  {
    id: 'FAC-14',
    name: 'Visakhapatnam Integrated Steel Works (RINL)',
    type: 'Steel Plant',
    operator: 'Rashtriya Ispat Nigam Ltd. (Vizag Steel)',
    operatingHours: '24/7 Blast Furnace 1-3 & Coke Oven Battery',
    location: {
      lat: 17.6095,
      lng: 83.2015,
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      country: 'India',
    },
    baselineFRP: 2.3,
    baselineStdDev: 0.65,
    baselineTi4K: 309.8,
    totalEvents30d: 14,
    currentRisk: 'MODERATE',
    currentStatus: 'NORMAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(17.6095, 83.2015, 0.025, 0.021),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(14, 2.3, 0.65, false, 1.74),
  },
  {
    id: 'FAC-15',
    name: 'Vindhyachal & Singrauli Super Thermal Power Hub',
    type: 'Power Plant',
    operator: 'NTPC Limited (4760 MW Ultra Mega Thermal Cluster)',
    operatingHours: '24/7 Base Load Supercritical Coal Boilers',
    location: {
      lat: 24.196,
      lng: 82.7166,
      city: 'Singrauli',
      state: 'Madhya Pradesh',
      country: 'India',
    },
    baselineFRP: 2.1,
    baselineStdDev: 0.6,
    baselineTi4K: 308.0,
    totalEvents30d: 11,
    currentRisk: 'LOW',
    currentStatus: 'NORMAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(24.196, 82.7166, 0.026, 0.022),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(15, 2.1, 0.6, false, 1.31),
  },
  {
    id: 'FAC-16',
    name: 'Korba Super Thermal & BALCO Aluminum Smelter Zone',
    type: 'Power Plant',
    operator: 'NTPC Korba & Bharat Aluminum Co. (BALCO)',
    operatingHours: '24/7 Thermal Generation & Electrolytic Smelting',
    location: {
      lat: 22.3224,
      lng: 82.577,
      city: 'Korba',
      state: 'Chhattisgarh',
      country: 'India',
    },
    baselineFRP: 2.2,
    baselineStdDev: 0.6,
    baselineTi4K: 307.5,
    totalEvents30d: 13,
    currentRisk: 'LOW',
    currentStatus: 'NORMAL',
    lastDetectedEventTime: new Date().toISOString(),
    coordinatesBoundary: buildFacilityPolygon(22.3224, 82.577, 0.026, 0.022),
    activeAnomaliesCount: 1,
    historicalThermalHistory: buildFacilityThermalHistory(16, 2.2, 0.6, false, 1.2),
  },
];
